#!/usr/bin/zsh
#
# install_modos -- install the `modo` scripts
#
# 2020-01-15    `l10nrestore` is now a zsh script.

emulate -L zsh

local binroot instopts localgroup

if (( EUID != 0 )); then
    print -- ${0:t}: Ylläpito-oikeudet vaaditaan\! 1>&2
    exit 1
fi

# Settings
grep -q staff /etc/group && localgroup=staff
grep -q wheel /etc/group && localgroup=wheel
: ${localgroup:=root}
binroot=/usr/local
instopts=(-g $localgroup -m 755)

do_install() {
    local dest src

    dest=$@[-1]
    for src in $@[1,-2]; do
        if [[ ! -f $dest/${src:r} || $src -nt $dest/${src:r} ]]; then
            print -- $src -\> $dest/${src:r}
            install $instopts $src $dest/${src:r}
        fi
    done
}

# Programs requiring superuser privileges
do_install modo qmdo l10nrestore $binroot/sbin

# Programs that don't require superuser privileges
do_install podo $binroot/bin
