#!/usr/bin/zsh
#
# install_modos -- install modo, qmdo and l10nrestore
#
# 2016-09-13    Ready. (TN)
# 2016-09-17    podo added. do_install function. (TN)
# 2016-09-18    No need to install unless source is newer. (TN)
# 2016-10-01    Bug fix: of course one needs to check if the files exist
#               before checking their age! (TN)
# 2017-01-30    Added $localgroup handling. (TN)

emulate -L zsh

local binroot instopts localgroup prgname

if [[ $EUID -ne 0 ]]; then
    print -- ${0:t}: Ei onnistu sudotta\! 1>&2
    exit 1
fi

# Which /usr/local group should we be using?
[[ grep -q staff /etc/group ]] && localgroup=staff
[[ grep -q wheel /etc/group ]] && localgroup=wheel
[[ -z $localgroup ]] && localgroup=root

# Constants
instopts=(-g $localgroup -m 755)
binroot=/usr/local
prgname=${0:t}

do_install() {
    local dest source
    local -a sources

    dest=$argv[1]
    sources=($argv[2,-1])
    for src in $sources; do
        if [[ ! -f $dest/${src:r} || $src -nt $dest/${src:r} ]]; then
            print -- $prgname: $src -\> $dest/${src:r}
            install $instopts $src $dest/${src:r}
        fi
    done
}

# Programs requiring superuser privileges
do_install $binroot/sbin modo qmdo l10nrestore.py

# Programs that don't require superuser privileges
do_install $binroot/bin podo
