#!/usr/bin/zsh
#
# install_modos -- install modo, tsdo and l10nrestore
#
# 2016-09-13    Ready. (TN)
# 2016-09-17    podo added. do_install function. (TN)

emulate -L zsh

if [[ $EUID -ne 0 ]]; then
    print -- ${0:t}: Ei onnistu ilman sudoa\! 1>&2
    exit 1
fi

instopts=(-g staff -m 755)
binroot=/usr/local

do_install() {
    local dest, source
    local -a sources
    
    dest=$argv[1]
    sources=($argv[2,-1])
    for source in $sources; do
        print -- ${0:t}: $source -\> $dest/$name
        install $instopts $source $dest/${source:r}
    done
}

# Programs requiring superuser privileges
do_install $binroot/sbin modo tsdo l10restore.py

# Programs that don't require superuser privileges
do_install $binroot/bin podo
