#!/usr/bin/zsh
#
# tsdo -- .ts-tiedoston asennus
#
# Muunnelma modo-skriptistä Qt:n käännösjärjestelmää varten. Kääntää
# muuttuneet .ts-tiedostot .qm-tiedostoiksi ja siirtää ne paikalleen.
#
# 2009-07-12    Projekti käynnistetty. (TN)
# 2016-01-24    Siirros zsh:hon. (TN)
# 2016-05-03    Lisätty -- kaikkiin print-komentoihin. (TN)
# 2016-09-13    Tehtiin pitkään odottaneita lisämuutoksia modon mallin
#               mukaisesti. (TN)

emulate -L zsh

tsdotemp=/tmp/$(whoami)

# Tarvitaan lrelease
if [[ -z "$(whence lrelease)" ]]; then
    print -- ${0:t}: asenna ensin qt4-dev-tools 1>&2
    exit 1
fi

# Asetetaan kohdekansio (tsdo.def on AINA annettava)
if [[ ! -e tsdo.def ]]; then
    print -- ${0:t}: kansiossa ei ole tsdo.def-tiedostoa 1>&2
    exit 1
else
    dest=$(<tsdo.def)
    print -- ${0:t}: kohdehakemisto "$dest"
fi

# Kerätään lähdetiedostot
if [[ $# -gt 0 ]]; then
    tsfiles=($@)
elif ls -1 | grep -q "\.ts\$"; then
    for tsfile in *.ts; do
        qmfile=$dest/${tsfile:t:r}.mo
        [[ ! -f $qmfile || $tsfile -nt $qmfile ]] && tsfiles=($tsfiles $tsfile)
    done
fi
if [[ ${#tsfiles} -eq 0 ]]; then
    print -- ${0:t}: Ei lähdetiedostoja 1>&2
    exit 0
fi

# Asetetaan väliaikaiskansio
if [[ ! -d $tsdotemp ]]; then
    if ! mkdir $tsdotemp > /dev/null 2>&1; then
        print -- ${0:t}: Väliaikaiskansion luonti ei onnistu 1>&2
        exit 3
    fi
elif ls -1 $tsdotemp | grep -q "\.qm\$"; then
    rm $modotemp/*.qm
fi

# Käännetään lähdetiedostot
for tsfile in $tsfiles; do
    tsname=${tsfile:t}
    qmfile=$tsdotemp/${tsname:r}.qm
    print -- ${0:t}: Käännetään $tsname...

    # Asennetaan kohdetiedosto
    if lrelease $tsfile -qm $qmfile > /dev/null 2>&1; then
        print -- ${0:t}: Kopioidaan $qmfile -\> $dest...
        sudo install --backup=numbered -o root -g root -m 444 $qmfile $dest
        rm $qmfile
    else
        print -- ${0:t}: Virhe\! 1>&2
    fi
done
